const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('cfg:get'),
  getRam: () => ipcRenderer.invoke('sys:ram'),
  appInfo: () => ipcRenderer.invoke('app:info'),
  legal: (d) => ipcRenderer.invoke('app:legal', d),
  setConfig: (cfg) => ipcRenderer.invoke('cfg:set', cfg),
  pickDir: () => ipcRenderer.invoke('pick:dir'),
  pickJava: () => ipcRenderer.invoke('pick:java'),
  pickFile: (o) => ipcRenderer.invoke('pick:file', o),
  listVersions: () => ipcRenderer.invoke('mc:versions'),
  versionInfo: (p) => ipcRenderer.invoke('mc:version-info', p),
  instanceSettingsGet: (p) => ipcRenderer.invoke('instance:settings-get', p),
  instanceSettingsSet: (p) => ipcRenderer.invoke('instance:settings-set', p),
  versionDelete: (p) => ipcRenderer.invoke('mc:version-delete', p),
  trashList: () => ipcRenderer.invoke('mc:trash-list'),
  trashRestore: (p) => ipcRenderer.invoke('mc:trash-restore', p),
  versionLibraries: (p) => ipcRenderer.invoke('mc:libraries', p),
  modsList: (p) => ipcRenderer.invoke('mods:list', p),
  modsToggle: (p) => ipcRenderer.invoke('mods:toggle', p),
  modsDelete: (p) => ipcRenderer.invoke('mods:delete', p),
  modsAdd: (p) => ipcRenderer.invoke('mods:add', p),
  modsOpen: (p) => ipcRenderer.invoke('mods:open', p),
  modSearch: (p) => ipcRenderer.invoke('mod:search', p),
  modVersions: (p) => ipcRenderer.invoke('mod:versions', p),
  modInstall: (p) => ipcRenderer.invoke('mod:install', p),
  checkUpdate: () => ipcRenderer.invoke('app:check-update'),
  checkUpdateP: (o) => ipcRenderer.invoke('app:check-update', o),
  downloadUpdate: (o) => ipcRenderer.invoke('app:download-update', o),
  installUpdate: (o) => ipcRenderer.invoke('app:install-update', o),
  autoUpdateSilent: (o) => ipcRenderer.invoke('app:auto-update', o),
  runUpdate: (o) => ipcRenderer.invoke('app:run-update', o),
  openUpdateFolder: () => ipcRenderer.invoke('app:open-update-folder'),
  onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (_e, d) => cb(d)),
  versionManifest: (p) => ipcRenderer.invoke('mc:manifest', p),
  sourceList: () => ipcRenderer.invoke('source:list'),
  searchAll: (p) => ipcRenderer.invoke('search:all', p),
  installVanilla: (p) => ipcRenderer.invoke('mc:install-vanilla', p),
  loaderVersions: (p) => ipcRenderer.invoke('loader:versions', p),
  loaderInstall: (p) => ipcRenderer.invoke('loader:install', p),
  addonVersions: (p) => ipcRenderer.invoke('addon:versions', p),
  addonInstall: (p) => ipcRenderer.invoke('addon:install', p),
  detectJava: () => ipcRenderer.invoke('java:detect'),
  requiredJava: (v) => ipcRenderer.invoke('java:required', v),
  launch: (opts) => ipcRenderer.invoke('mc:launch', opts),
  openPath: (p) => ipcRenderer.invoke('shell:open', p),
  minimizeWin: () => ipcRenderer.invoke('win:minimize'),
  showWin: () => ipcRenderer.invoke('win:show'),
  notify: (o) => ipcRenderer.invoke('notify', o),

  // 存档 / 实例备份 / 截图 / 导入
  worldList: () => ipcRenderer.invoke('world:list'),
  worldBackup: (p) => ipcRenderer.invoke('world:backup', p),
  worldBackups: (p) => ipcRenderer.invoke('world:backups', p),
  worldRestore: (p) => ipcRenderer.invoke('world:restore', p),
  worldDelete: (p) => ipcRenderer.invoke('world:delete', p),
  worldBackupDelete: (p) => ipcRenderer.invoke('world:backup-delete', p),
  worldOpen: () => ipcRenderer.invoke('world:open'),
  serverWorldInfo: () => ipcRenderer.invoke('server-world:info'),
  serverWorldBackup: (p) => ipcRenderer.invoke('server-world:backup', p),
  serverWorldBackups: () => ipcRenderer.invoke('server-world:backups'),
  serverWorldRestore: (p) => ipcRenderer.invoke('server-world:restore', p),
  serverWorldBackupDelete: (p) => ipcRenderer.invoke('server-world:backup-delete', p),
  serverWorldOpen: () => ipcRenderer.invoke('server-world:open'),
  serverAutoBackupGet: () => ipcRenderer.invoke('server-auto-backup:get'),
  serverAutoBackupSet: (p) => ipcRenderer.invoke('server-auto-backup:set', p),
  serverAutoBackupRunNow: () => ipcRenderer.invoke('server-auto-backup:run-now'),
  serverUpdateCheck: () => ipcRenderer.invoke('server-update:check'),
  serverUpdateApply: () => ipcRenderer.invoke('server-update:apply'),
  instanceBackup: (p) => ipcRenderer.invoke('instance:backup', p),
  instanceBackups: (p) => ipcRenderer.invoke('instance:backups', p),
  instanceRestore: (p) => ipcRenderer.invoke('instance:restore', p),
  instanceBackupDelete: (p) => ipcRenderer.invoke('instance:backup-delete', p),
  shotList: () => ipcRenderer.invoke('shot:list'),
  shotOpen: () => ipcRenderer.invoke('shot:open'),
  shotShow: (p) => ipcRenderer.invoke('shot:show', p),
  importList: () => ipcRenderer.invoke('import:list'),
  importVersion: (p) => ipcRenderer.invoke('import:version', p),

  // 资源包
  rpackSearch: (p) => ipcRenderer.invoke('rpack:search', p),
  rpackVersions: (p) => ipcRenderer.invoke('rpack:versions', p),
  rpackInstall: (p) => ipcRenderer.invoke('rpack:install', p),
  rpackList: () => ipcRenderer.invoke('rpack:list'),
  rpackOpen: () => ipcRenderer.invoke('rpack:open'),

  // mod 更新检查
  modCheckUpdates: (p) => ipcRenderer.invoke('mod:check-updates', p),

  // 皮肤 / 披风
  skinInfo: (p) => ipcRenderer.invoke('skin:info', p),
  skinUpload: (p) => ipcRenderer.invoke('skin:upload', p),
  skinSetCape: (p) => ipcRenderer.invoke('skin:set-cape', p),

  // 微软正版登录
  msStart: () => ipcRenderer.invoke('auth:ms-start'),
  msPoll: () => ipcRenderer.invoke('auth:ms-poll'),
  msRefresh: (o) => ipcRenderer.invoke('auth:ms-refresh', o),
  msLogout: (o) => ipcRenderer.invoke('auth:ms-logout', o),
  accounts: () => ipcRenderer.invoke('auth:accounts'),
  switchAccount: (o) => ipcRenderer.invoke('auth:switch', o),
  removeAccount: (o) => ipcRenderer.invoke('auth:remove', o),
  account: () => ipcRenderer.invoke('auth:account'),
  onAuthStatus: (cb) => ipcRenderer.on('auth:status', (_e, d) => cb(d)),

  // 整合包
  packSearch: (p) => ipcRenderer.invoke('pack:search', p),
  packTop: (p) => ipcRenderer.invoke('pack:top', p),
  packVersions: (p) => ipcRenderer.invoke('pack:versions', p),
  packInstallFull: (p) => ipcRenderer.invoke('pack:install-full', p),
  projectDetail: (p) => ipcRenderer.invoke('project:detail', p),

  // 光影包
  shaderSearch: (p) => ipcRenderer.invoke('shader:search', p),
  shaderVersions: (p) => ipcRenderer.invoke('shader:versions', p),
  shaderInstallFull: (p) => ipcRenderer.invoke('shader:install-full', p),

  onInstallLog: (cb) => ipcRenderer.on('install:log', (_e, d) => cb(d)),
  onInstallProgress: (cb) => ipcRenderer.on('install:progress', (_e, d) => cb(d)),
  onInstallDone: (cb) => ipcRenderer.on('install:done', (_e, d) => cb(d)),

  // 服务器
  serverCreate: (o) => ipcRenderer.invoke('server:create', o),
  serverVersions: (p) => ipcRenderer.invoke('server:versions', p),
  serverStatus: () => ipcRenderer.invoke('server:status'),
  serverQuickDefaults: () => ipcRenderer.invoke('server:quick-defaults'),
  serverInfo: (o) => ipcRenderer.invoke('server:info', o),
  serverStart: (o) => ipcRenderer.invoke('server:start', o),
  serverStop: () => ipcRenderer.invoke('server:stop'),
  serverCmd: (c) => ipcRenderer.invoke('server:cmd', c),
  serverUpdateProps: (o) => ipcRenderer.invoke('server:update-props', o),
  serverSay: (o) => ipcRenderer.invoke('server:say', o),
  serverOnline: () => ipcRenderer.invoke('server:online'),
  serverRefreshOnline: () => ipcRenderer.invoke('server:refresh-online'),
  serverList: () => ipcRenderer.invoke('server:list'),
  serverAdd: (o) => ipcRenderer.invoke('server:add', o),
  serverRemove: (o) => ipcRenderer.invoke('server:remove', o),
  serverSwitch: (o) => ipcRenderer.invoke('server:switch', o),
  serverRename: (o) => ipcRenderer.invoke('server:rename', o),
  srvModList: (o) => ipcRenderer.invoke('srvmod:list', o),
  srvModInstall: (o) => ipcRenderer.invoke('srvmod:install', o),
  srvModToggle: (o) => ipcRenderer.invoke('srvmod:toggle', o),
  srvModDelete: (o) => ipcRenderer.invoke('srvmod:delete', o),
  srvModOpen: (o) => ipcRenderer.invoke('srvmod:open', o),
  onSrvModProgress: (cb) => ipcRenderer.on('srvmod:progress', (_e, d) => cb(d)),
  onServerChat: (cb) => ipcRenderer.on('server:chat', (_e, d) => cb(d)),
  onServerOnline: (cb) => ipcRenderer.on('server:online', (_e, d) => cb(d)),
  onServerAutoBackup: (cb) => ipcRenderer.on('server:autobackup', (_e, d) => cb(d)),
  onPackZhName: (cb) => ipcRenderer.on('pack:zhname', (_e, d) => cb(d)),

  // 内网穿透
  tunnelDownload: () => ipcRenderer.invoke('tunnel:download'),
  tunnelStart: (c) => ipcRenderer.invoke('tunnel:start', c),
  tunnelStop: () => ipcRenderer.invoke('tunnel:stop'),
  tunnelStatus: () => ipcRenderer.invoke('tunnel:status'),
  onTunnelLog: (cb) => ipcRenderer.on('tunnel:log', (_e, d) => cb(d)),

  onLog: (cb) => ipcRenderer.on('mc:log', (_e, d) => cb(d)),
  onProgress: (cb) => ipcRenderer.on('mc:progress', (_e, d) => cb(d)),
  onClose: (cb) => ipcRenderer.on('mc:close', (_e, d) => cb(d)),
  onCollectGarbage: (cb) => ipcRenderer.on('mc:collect', () => cb()),
  onServerLog: (cb) => ipcRenderer.on('server:log', (_e, d) => cb(d)),
  onServerProgress: (cb) => ipcRenderer.on('server:progress', (_e, d) => cb(d))
});
