// zhsearch.js - 中文搜索优化
// Modrinth / CurseForge 只认英文，中文关键词直接搜通常 0 结果。
// 这里维护一份「中文 → 英文关键词」词典，把中文查询扩展成英文再搜，
// 同时保留原词，最后合并去重，让中文搜索也能命中常用 Mod / 整合包 / 光影。

const fs = require('fs');
const path = require('path');

// ---------- 中文 → 英文关键词词典 ----------
// 值是候选英文词数组（按优先级）。可多个，扩大召回。
const ZH_TO_EN = {
  // —— 性能 / 优化 ——
  '优化': ['optimization', 'performance', 'optimized', 'fps'],
  '性能': ['performance', 'optimization', 'fps'],
  '流畅': ['fps', 'performance', 'sodium', 'optifine'],
  '帧数': ['fps', 'framerate', 'sodium'],
  '加速': ['performance', 'optimization', 'acceleration'],
  '渲染': ['render', 'rendering', 'sodium'],
  '光影': ['shader', 'shaders'],
  '着色器': ['shader', 'shaders'],
  '整合包': ['modpack', 'mod pack'],
  '模组包': ['modpack'],
  '材质': ['texture', 'resourcepack', 'resource pack'],
  '材质包': ['resourcepack', 'resource pack', 'texture pack'],
  '资源包': ['resourcepack', 'resource pack'],
  '皮肤': ['skin', 'skins'],
  '披风': ['cape', 'capes'],
  // —— 常用知名 Mod（中文俗称 → 英文名）——
  '钠': ['sodium'],
  '钠锂': ['sodium', 'lithium'],
  '锂': ['lithium'],
  '磷': ['phosphor'],
  '镁': ['magnesium'],
  '铷': ['rubidium'],
  '氪': ['krypton'],
  '铁氧': ['ferritecore'],
  '铁氧体': ['ferritecore'],
  '优化模组': ['optimization', 'performance'],
  '强化': ['enhanced', 'improved'],
  '铱': ['iridium'],
  '钇': ['yttrium'],
  '内存': ['memory'],
  '快速加载': ['fastload', 'better loading'],
  // 常用功能性 mod
  '小地图': ['minimap', 'xaeros'],
  '地图': ['map', 'minimap'],
  '旅行地图': ['journeymap', 'minimap'],
  '机械动力': ['create'],
  '创造': ['create'],
  '物联网': ['create'],
  '合成': ['crafting', 'craft'],
  '合成表': ['jei', 'nei', 'recipe'],
  '配方': ['recipe', 'jei'],
  '物品管理器': ['jei', 'roughly enough items', 'rei'],
  '背包': ['backpack', 'inventory'],
  '仓库': ['storage', 'warehouse'],
  '存储': ['storage'],
  '箱子': ['chest', 'storage'],
  '应用能源': ['applied energistics', 'ae2'],
  '工业': ['industrial', 'ic2'],
  '匠魂': ['tinkers', 'construct'],
  '神秘': ['thaumcraft'],
  '暮色': ['twilight forest'],
  '暮色森林': ['twilight forest'],
  '天堂': ['aether'],
  '以太': ['aether'],
  '更多': ['more', 'extra'],
  '更多武器': ['more weapons', 'extra weapons'],
  '拔刀剑': ['slashblade', 'katana'],
  '精英怪': ['elite mobs'],
  '怪物': ['mob', 'mobs', 'monster'],
  '生物': ['mob', 'creature', 'mobs'],
  '动物': ['animal', 'animals'],
  '村庄': ['village'],
  '建筑': ['building', 'build', 'construction'],
  '建筑杖': ['building wand', 'building gadget'],
  '地牢': ['dungeon', 'dungeons'],
  '探索': ['exploration', 'adventure'],
  '维度': ['dimension', 'dimensions'],
  '末地': ['end', 'ender'],
  '下界': ['nether'],
  '地狱': ['nether'],
  '农业': ['farming', 'agriculture'],
  '农夫': ['farmer', 'farming'],
  '食物': ['food', 'foods'],
  '烹饪': ['cooking', 'cook'],
  '料理': ['cooking'],
  '钓鱼': ['fishing', 'fish'],
  '附魔': ['enchant', 'enchantment'],
  '装备': ['equipment', 'gear', 'armor'],
  '盔甲': ['armor'],
  '武器': ['weapon', 'weapons'],
  '工具': ['tool', 'tools'],
  '魔法': ['magic', 'magical'],
  '科技': ['tech', 'technology'],
  '能源': ['energy', 'power'],
  '发电机': ['generator'],
  '管道': ['pipe', 'pipes', 'pipez'],
  '自动化': ['automation', 'auto'],
  '局域网': ['lan', 'multiplayer'],
  '联机': ['multiplayer', 'server'],
  '服务器': ['server', 'multiplayer'],
  '建筑党': ['building'],
  '红石': ['redstone'],
  '逻辑': ['logic'],
  '电路': ['circuit', 'redstone'],
  '交通': ['transport', 'transportation'],
  '载具': ['vehicle', 'vehicles'],
  '飞行': ['flight', 'fly'],
  '背包整理': ['inventory sorting', 'inventory'],
  '整理': ['sort', 'sorting', 'inventory'],
  '经验': ['experience', 'xp'],
  '血量': ['health', 'hp'],
  '生命': ['health', 'life'],
  '饥饿': ['hunger'],
  '状态': ['status', 'hud'],
  '界面': ['ui', 'hud', 'interface'],
  '抬头显示': ['hud'],
  '信息': ['info', 'information', 'hud'],
  '提示': ['tooltip', 'tips', 'hud'],
  '日志': ['log'],
  '设置': ['config', 'settings'],
  '配置': ['config', 'configuration'],
  '汉化': ['chinese', 'translation', 'chinese translation'],
  '最后': ['last'],
  '空岛': ['skyblock', 'sky block', 'island'],
  '生存': ['survival'],
  '冒险': ['adventure'],
  '科技': ['tech', 'technology'],
  '魔法': ['magic', 'magical'],
  '挑战': ['challenge'],
  '硬核': ['hardcore'],
  '互通': ['compatibility', 'compat'],
  '搞笑': ['funny', 'fun'],
  '休闲': ['casual', 'relaxing'],
  '像素': ['pixel', 'pixelmon'],
  '工业': ['industrial', 'ic2', 'gregtech'],
  '原版': ['vanilla'],
  '生存整合': ['survival', 'modpack'],
  '光影整合': ['shader', 'modpack'],
  '低配': ['low end', 'performance', 'optimization'],
  '高配': ['high end', 'shader', 'realistic'],
  '电影': ['cinematic', 'shader'],
  '真实': ['realistic', 'shader'],
  '写实': ['realistic', 'shader'],
  '卡通': ['cartoon', 'toon', 'cel'],
  '水反': ['water reflection', 'reflection', 'shader'],
  '云影': ['cloud shadow', 'shader'],
  '泛光': ['bloom', 'shader'],
  '景深': ['depth of field', 'shader'],
  '动态光': ['dynamic light', 'shader'],
  '中文': ['chinese', 'chinese translation', 'translation'],
  '翻译': ['translation', 'translate'],
  '指令': ['command', 'commands'],
  '命令': ['command', 'commands'],
  '作弊': ['cheat', 'cheats'],
  '创造模式': ['creative'],
  '生存': ['survival'],
  '困难': ['hardcore', 'hard'],
  '死亡': ['death', 'deaths'],
  '掉落': ['drop', 'drops', 'loot'],
  '战利品': ['loot', 'loottable'],
  '宝藏': ['treasure', 'loot'],
  '灾厄': ['illager', 'raid'],
  '掠夺': ['raid', 'pillager'],
  '头像': ['avatar', 'face'],
  '设置界面': ['config screen', 'mod menu'],
  '菜单': ['menu', 'mod menu'],
  '模组菜单': ['mod menu'],
  '模组': ['mod', 'mods'],
  '插件': ['plugin', 'plugins'],
  '控制': ['controller', 'gamepad', 'control'],
  '手柄': ['controller', 'gamepad'],
  '鼠标': ['mouse'],
  '键位': ['keybind', 'keybinds', 'key'],
  '分辨率': ['resolution'],
  '截图': ['screenshot', 'screenshots'],
  '相机': ['camera', 'cameras'],
  '视角': ['camera', 'view', 'perspective'],
  '第一人称': ['first person', 'firstperson'],
  '第三人称': ['third person'],
  '缩放': ['zoom'],
  '准星': ['crosshair'],
  '天空': ['sky', 'skies'],
  '云': ['cloud', 'clouds'],
  '天气': ['weather'],
  '季节': ['season', 'seasons'],
  '水体': ['water'],
  '水面': ['water', 'shader'],
  '夜间': ['night'],
  '夜空': ['night sky', 'sky'],
  '生物群系': ['biome', 'biomes'],
  '世界生成': ['worldgen', 'world generation'],
  '地形': ['terrain', 'worldgen'],
  '结构': ['structure', 'structures'],
  '矿石': ['ore', 'ores'],
  '矿物': ['ore', 'mineral'],
  '挖掘': ['mining', 'mine'],
  '采集': ['harvest', 'gather'],
  '树': ['tree', 'trees'],
  '植物': ['plant', 'plants'],
  '花': ['flower', 'flowers'],
  '敌人': ['enemy', 'enemies', 'mob'],
  'boss': ['boss'],
  '宠物': ['pet', 'pets'],
  '坐骑': ['mount', 'mounts'],
  '召唤': ['summon', 'summoning'],
  '技能': ['skill', 'skills', 'abilities'],
  '天赋': ['talent', 'talents'],
  '等级': ['level', 'leveling'],
  '经验值': ['experience', 'xp']
};

// 英文反查（当用户输入中文但词典只有精确子串时，做包含匹配）
const ZH_KEYS = Object.keys(ZH_TO_EN).sort((a, b) => b.length - a.length);

// 判断是否包含中文
function hasChinese(s) {
  return /[\u4e00-\u9fff]/.test(String(s || ''));
}

// 把中文查询扩展成英文关键词数组（最多 maxTerms 个）
function expandQuery(query, maxTerms = 4) {
  const q = String(query || '').trim();
  if (!hasChinese(q)) return [];
  const out = [];
  const push = (w) => { if (w && !out.includes(w)) out.push(w); };
  // 1) 先做整词精确匹配
  if (ZH_TO_EN[q]) for (const w of ZH_TO_EN[q]) push(w);
  // 2) 再做包含匹配（长键优先），如「性能优化」命中「优化」「性能」
  for (const key of ZH_KEYS) {
    if (out.length >= maxTerms) break;
    if (q.includes(key)) for (const w of ZH_TO_EN[key]) push(w);
  }
  // 3) 去掉纯中文残留词
  return out.filter((w) => w && !hasChinese(w)).slice(0, maxTerms);
}

module.exports = { expandQuery, hasChinese, ZH_TO_EN };
