name: Check

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm install --include=dev
        env:
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
      - name: Run static checks
        run: node check.js
